language: cpp

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - name: CUDA 8
      env:
      - CUDA=8.0.61-1
      - CUDA_SHORT=8.0
      - CUDA_APT=8-0
      - UBUNTU_VERSION=ubuntu1604
      dist: xenial
    - name: CUDA 9
      env:
      - CUDA=9.2.148-1
      - CUDA_SHORT=9.2
      - CUDA_APT=9-2
      - UBUNTU_VERSION=ubuntu1604
      dist: xenial
    - name: CUDA 10
      env:
      - CUDA=10.1.105-1
      - CUDA_APT=10-1
      - CUDA_SHORT=10.1
      - UBUNTU_VERSION=ubuntu1804
      dist: bionic

before_install:
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-cufft-dev-${CUDA_APT}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${CUDA_HOME}/stubs:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  - sudo ln -s $CUDA_HOME /usr/local/cuda
  - sudo ldconfig
  - echo $LD_LIBRARY_PATH
  - sudo find / -name libcuda.so


script:
    - ./build.sh
